### ISSUE TITLE
Final checklist 

### ISSUE THREAD

**Issue by nehalbhanushali** [vasantivmahajan/DataWrangling_AnomalyDetection_Tableau_Visualization_EDGAR_Log_Data#8]
- [ ] delete temp code

- [ ] remove restrictions if any to reduce number of files being handled 

- [ ] fetch values from config where ever possible. (verify if cik accession need to come from config or input: we have both :))

- [ ] remove unwanted prints

- [ ] for alert function on cik hits through the year, use the csv made by vasanti instead of 2003/2003.csv and use the joined df ( company +cik df )
